/** External link posts for the blog — these link offsite rather than to local content. */
export interface BlogLink {
  id: string;
  title: string;
  date: string;
  author: string;
  description: string;
  url: string;
  tags: string[];
  /** Minor posts render as a simple one-line link with no author/description */
  minor?: boolean;
}

export const blogLinks: BlogLink[] = [
  {
    id: 'geotessera-v0.8.0',
    title: 'geotessera v0.8.0: Zarr v3 store, GeoTIFF memory fixes, and registry improvements',
    date: '2026-04-05',
    author: 'geotessera',
    description: 'Adds cloud-native Zarr v3 access via GeoTesseraZarr with automatic UTM zone routing and point sampling, fixes GeoTIFF memory leaks for large regions, adds download resume for GeoTIFFs, and improves registry scanning with truncated file detection and selective parquet generation. Next up: extended registry support for multiple mirrors, versions, and formats.',
    url: 'https://github.com/ucam-eo/geotessera/releases/tag/v0.8.0',
    tags: ['release', 'python'],
  },
  {
    id: 'tessera-embeddings-convention',
    title: 'TESSERA adopts the Zarr geo-embeddings convention',
    date: '2026-03-27',
    author: 'Anil Madhavapeddy',
    description: 'TESSERA will migrate from separate annual stores to a unified MegaZarr with time as a primary dimension, adopting the emerging geo-embeddings Zarr convention for broader compatibility across embedding models.',
    url: 'https://anil.recoil.org/notes/tessera-embeddings-convention',
    tags: ['engineering'],
  },
  {
    id: 'pixels-to-embeddings-customisation',
    title: 'From Pixels to Embeddings: TESSERA Customisation',
    date: '2026-03-25',
    author: 'Gijs van den Dool',
    description: 'A contributed walkthrough of a custom Master-Worker pipeline for running TESSERA inference in Google Colab, with analysis of optimal cloud cover thresholds for West Africa.',
    url: 'https://www.linkedin.com/pulse/from-pixels-embeddings-tessera-earth-observation-gijs-van-den-dool-uti7e/',
    tags: ['community'],
    minor: true,
  },
  {
    id: 'tee-v3.4-v3.5',
    title: 'TEE v3.4 and v3.5: Manual labelling and multi-user login',
    date: '2026-03-24',
    author: 'Srinivasan Keshav',
    description: 'Two releases of the TESSERA Embedding Explorer: v3.4 adds manual labelling with pin and polygon tools, per-class similarity sliders, and spatial classifiers. v3.5 adds a multi-user login system to the demo site — request access via the TESSERA channel on eeg.zulipchat.com. See also the walkthroughs of TEE in the videos section.',
    url: 'https://github.com/ucam-eo/TEE/releases/tag/v3.5.0',
    tags: ['release', 'tee'],
  },
  {
    id: 'geospatial-skills-claude',
    title: 'Claude Code skills for geospatial analysis with TESSERA',
    date: '2026-03-20',
    author: 'Isaac Corley',
    description: 'A set of Claude Code skills for working with TESSERA embeddings via the Python and R libraries, enabling AI-assisted geospatial analysis workflows.',
    url: 'https://isaac.earth/geospatial-skills',
    tags: ['community', 'engineering'],
  },
  {
    id: 'tessera-zarr-v3-layout',
    title: 'Streaming millions of TESSERA tiles over HTTP with Zarr v3',
    date: '2026-03-14',
    author: 'Anil Madhavapeddy',
    description: 'How TESSERA restructured its geospatial embeddings from millions of individual files into sharded Zarr v3 stores, enabling efficient HTTP streaming via range requests for both single-pixel mobile queries and large-scale regional analysis.',
    url: 'https://anil.recoil.org/notes/tessera-zarr-v3-layout',
    tags: ['engineering'],
  },
  {
    id: 'pixels-to-patches-pooling',
    title: 'Paper: From Pixels to Patches — Pooling Strategies for Earth Embeddings',
    date: '2026-03-02',
    author: 'Isaac Corley et al.',
    description: 'Introduces EuroSAT-Embed, a dataset of 81k embedding GeoTIFFs from three models, and evaluates 13 pooling approaches. Recommends Generalized Mean Pooling as an efficient alternative to mean pooling, reducing geographic generalization gap by up to 40%.',
    url: 'https://arxiv.org/abs/2603.02080',
    tags: ['research', 'community'],
    minor: true,
  },
  {
    id: 'oxcaml-inference',
    title: 'ONNX inference engine using OxCaml\'s SIMD intrinsics',
    date: '2026-03-13',
    author: 'Mark Elvers',
    description: 'Building a zero-allocation ONNX inference engine for the TESSERA model using OxCaml\'s unboxed float32 types and SIMD intrinsics. Achieves ~200ms single-threaded latency, within 2.2x of ONNX Runtime.',
    url: 'https://www.tunbury.org/2026/03/13/oxcaml-inference/',
    tags: ['engineering'],
  },
  {
    id: 'tee-v3.2.0',
    title: 'TEE v3.2.0: GPU-accelerated U-Net classifier and flip augmentation',
    date: '2026-03-13',
    author: 'Srinivasan Keshav',
    description: 'Adds a GPU-accelerated U-Net classifier operating on full 2D embedding grids via PyTorch with CUDA, MPS, and CPU support. Introduces 4\u00d7 flip augmentation for Spatial MLP 3\u00d73 and 5\u00d75 variants, plus improved error handling for non-JSON server responses.',
    url: 'https://github.com/ucam-eo/TEE/releases/tag/v3.2.0',
    tags: ['release', 'web'],
  },
  {
    id: 'core-stack-hackathon',
    title: 'TESSERA and CoRE Stack Hackathon on Geospatial AI',
    date: '2026-02-19',
    author: 'CoRE Stack',
    description: '',
    url: 'https://core-stack.org/tessera-and-core-stack-hackathon-on-geospatial-ai/',
    tags: ['community', 'hackathon'],
    minor: true,
  },
  {
    id: 'core-stack-innovation-challenge',
    title: 'First round of Innovation Challenge Advances',
    date: '2026-02-23',
    author: 'CoRE Stack',
    description: '',
    url: 'https://core-stack.org/first-round-of-innovation-challenge-advances/',
    tags: ['community', 'hackathon'],
    minor: true,
  },
  {
    id: 'tech-debt-embeddings',
    title: 'The Technical Debt of Earth Embedding Products',
    date: '2026-02-28',
    author: 'Isaac Corley',
    description: '',
    url: 'https://cloudnativegeo.org/blog/2026/02/the-technical-debt-of-earth-embedding-products/',
    tags: ['community'],
    minor: true,
  },
  {
    id: 'gpu-vs-cpu',
    title: 'GPU vs CPU for ONNX Inference: NVIDIA L4 vs AMD EPYC 9965',
    date: '2026-03-11',
    author: 'Mark Elvers',
    description: 'Benchmarking TESSERA inference on GPU vs CPU, finding that NUMA-aware parallel CPU jobs can achieve 2x the aggregate throughput of a single GPU for satellite tile processing.',
    url: 'https://www.tunbury.org/2026/03/11/gpu-vs-cpu/',
    tags: ['engineering'],
  },
  {
    id: 'ocaml-tessera-notebook',
    title: 'Weeknotes 2026 week 10',
    date: '2026-03-08',
    author: 'Jon Ludlam',
    description: 'An interactive TESSERA notebook running in the browser using OCaml, js_top_worker and odoc plugins — enabling geospatial mapping and ML inference with ONNX web runtime bindings.',
    url: 'https://jon.recoil.org/blog/2026/03/weeknotes-2026-10.html',
    tags: ['engineering', 'ocaml'],
  },
  {
    id: 'fpl-post-bacc-fellowship',
    title: 'Applications Open: Post-Baccalaureate Fellowship',
    date: '2026-03-06',
    author: 'FP Launchpad',
    description: '',
    url: 'https://fplaunchpad.org/2026/03/06/applications-open-post-bacc-fellowship.html',
    tags: ['community'],
    minor: true,
  },
  {
    id: 'streaming-tessera-w10',
    title: 'Streaming TESSERA working, biodiversity action papers, and FPL takes off',
    date: '2026-03-08',
    author: 'Anil Madhavapeddy',
    description: 'A browser-based streaming interface for TESSERA satellite embeddings performing client-side analysis using WebGPU and WebAssembly.',
    url: 'https://anil.recoil.org/notes/2026w10',
    tags: ['engineering', 'web'],
  },
  {
    id: 'browser-tessera-w9',
    title: 'Browser TESSERA, package management and Docker in the CACM',
    date: '2026-03-01',
    author: 'Anil Madhavapeddy',
    description: 'Progress on TESSERA with Zarr streaming support enabling browser-based ML pipelines, plus a Docker paper making the CACM cover.',
    url: 'https://anil.recoil.org/notes/2026w9',
    tags: ['engineering', 'web'],
  },
  {
    id: 'tessera-pipeline',
    title: 'Tessera Pipeline',
    date: '2026-02-25',
    author: 'Mark Elvers',
    description: 'A technical walkthrough of the Tessera pipeline, processing Sentinel-1 and Sentinel-2 satellite imagery to generate machine learning embeddings.',
    url: 'https://www.tunbury.org/2026/02/25/teserra-pipeline/',
    tags: ['engineering'],
  },
  {
    id: 'first-tessera-hackathon',
    title: '1st TESSERA/CoRE hackathon at the Indian AI Summit',
    date: '2026-02-19',
    author: 'Anil Madhavapeddy',
    description: 'The inaugural TESSERA hackathon at the Indian AI Impact Summit in Delhi, exploring integration with IIT-Delhi\'s CoRE Stack for environmental monitoring.',
    url: 'https://anil.recoil.org/notes/first-tessera-hackathon',
    tags: ['community', 'hackathon'],
  },
  {
    id: 'ocaml-tessera',
    title: 'Tessera pipeline in OCaml',
    date: '2026-02-15',
    author: 'Mark Elvers',
    description: 'An OCaml implementation of the Tessera pipeline achieving 9.5x faster inference than the Python CPU baseline with GPU acceleration.',
    url: 'https://www.tunbury.org/2026/02/15/ocaml-tessera/',
    tags: ['engineering', 'ocaml'],
  },
  {
    id: 'lcz-weekly-notes',
    title: 'Weekly Notes: Local Climate Zones and road mapping with TESSERA',
    date: '2026-02-15',
    author: 'Andres C. Zuniga-Gonzalez',
    description: 'Work on Local Climate Zone classification using satellite imagery, challenges with dataset labeling, and progress on OpenStreetMap road mapping.',
    url: 'https://ancazugo.github.io/posts/2026-02-15-weekly-notes.html',
    tags: ['research', 'classification'],
  },
  {
    id: 'vivas-aria-w6',
    title: 'Vivas, ARIA and interviews',
    date: '2026-02-08',
    author: 'Anil Madhavapeddy',
    description: 'A doctoral viva, presenting research projects at ARIA, media coverage of conservation evidence work, and a CACM video interview.',
    url: 'https://anil.recoil.org/notes/2026w6',
    tags: ['community'],
  },
  {
    id: 'red-pill-conservation',
    title: 'Discussing effective conservation with all the UK Chief Scientists',
    date: '2026-02-03',
    author: 'Anil Madhavapeddy',
    description: 'Hosting UK nature conservation body leaders at Pembroke to present TESSERA, focusing on evidence-based approaches and transparent AI for conservation.',
    url: 'https://anil.recoil.org/notes/red-pill-conservation',
    tags: ['conservation', 'community'],
  },
  {
    id: 'ai4nature-launch',
    title: 'Ai4Nature officially launched: from shared principles to collective action',
    date: '2026-01-14',
    author: 'Anastasia Filatova',
    description: 'The Ai4Nature Alliance launch event bringing together ecological and technology leaders to establish frameworks for using AI responsibly in nature recovery.',
    url: 'https://ai4nature.org/the-alliance-journal/usot739onqmh3n43tgt3r8b9m6j3ye',
    tags: ['conservation', 'community'],
  },
  {
    id: 'amd-techtalk-vultr-tessera',
    title: 'Podcast: Accelerating Environmental and AI Research with Vultr',
    date: '2026-01-14',
    author: 'AMD TechTalk',
    description: '',
    url: 'https://open.spotify.com/episode/3ZlkQoPsO3XRHxA3Hdc7Sr',
    tags: ['community'],
    minor: true,
  },
  {
    id: 'solar-farms-tiny-model',
    title: 'Earth Observation on a Budget: Finding Solar Farms with a 42k-Parameter Model',
    date: '2026-01-14',
    author: 'Sadiq Jaffer',
    description: 'Detecting and mapping solar farms across the UK using satellite imagery and a compact 42k-parameter neural network, leveraging pre-trained TESSERA embeddings.',
    url: 'https://toao.com/blog/earth-observation-budget-solar-farms-tiny-model',
    tags: ['research', 'classification'],
  },
  {
    id: 'swiss-data-cube-geoembeddings',
    title: 'Geoembeddings of Switzerland',
    date: '2025-12-03',
    author: 'Swiss Data Cube',
    description: '',
    url: 'https://www.swissdatacube.org/index.php/2025/12/03/geoembeddings-for-switzerland/',
    tags: ['community'],
    minor: true,
  },
  {
    id: 'linkedin-ieee-grss-webinar',
    title: 'IEEE GRSS webinar on TESSERA precomputed FAIR global pixel embeddings',
    date: '2025-12-04',
    author: 'IEEE GRSS',
    description: '',
    url: 'https://www.linkedin.com/posts/ieee-grss_ieeegrss-grsswebinar-esi-activity-7402335630942527489-R8qn',
    tags: ['social', 'community'],
    minor: true,
  },
  {
    id: 'linkedin-atzberger-embeddings',
    title: 'What is the meaning of spectral-temporal embeddings?',
    date: '2025-12-08',
    author: 'Clement Atzberger',
    description: '',
    url: 'https://www.linkedin.com/posts/clement-atzberger-8abb8065_fun-question-what-is-the-meaninginterpretation-activity-7403754770894835712-cMfR',
    tags: ['social', 'research'],
    minor: true,
  },
  {
    id: 'tessera-stac',
    title: 'Tile Server',
    date: '2025-12-02',
    author: 'Mark Elvers',
    description: 'A scalable tile server using Parquet files and Arrow libraries to efficiently query geographic tiles through a simple API.',
    url: 'https://www.tunbury.org/2025/12/02/tessera-stac/',
    tags: ['engineering'],
  },
  {
    id: 'foundational-ecosystem-workshop',
    title: 'Foundational AI for Ecosystem Resilience Workshop',
    date: '2025-12-03',
    author: 'Anil Madhavapeddy',
    description: 'Report from two Cambridge Conservation Initiative workshops exploring how TESSERA and LLM-based simulations can enhance ecosystem resilience forecasting and conservation policy.',
    url: 'https://anil.recoil.org/notes/foundational-ecosystem-workshop',
    tags: ['conservation', 'community'],
  },
  {
    id: 'tessera-zarr',
    title: 'TESSERA and Zarr',
    date: '2025-11-30',
    author: 'Mark Elvers',
    description: 'Exploring TESSERA\'s NPY tile format and converting to Zarr for cloud-native chunked storage, with a survey of STAC and CF Conventions for standardised metadata.',
    url: 'https://www.tunbury.org/2025/11/30/tessera-zarr/',
    tags: ['engineering'],
  },
  {
    id: 'tessera-nairobi-example',
    title: 'TESSERA Infrastructure Detection in Nairobi',
    date: '2025-11-16',
    author: 'Andres C. Zuniga-Gonzalez',
    description: '',
    url: 'https://ancazugo.github.io/posts/2025-11-16-tessera_example.html',
    tags: ['research', 'classification'],
    minor: true,
  },
  {
    id: 'video-propl-embeddings',
    title: 'Video: Building a Usable Library for Planetary-Scale Embeddings (PROPL\'25)',
    date: '2025-10-05',
    author: 'Sadiq Jaffer',
    description: 'PROPL workshop talk at ICFP/SPLASH demonstrating how GeoTessera makes planetary-scale remote sensing accessible, including a live solar farm classification demo.',
    url: 'https://watch.eeg.cl.cam.ac.uk/w/trq77gFwc8ZbUeGqyDpzN7',
    tags: ['video', 'community'],
  },
  {
    id: 'icfp25-propl',
    title: 'Programming for the Planet at ICFP/SPLASH 2025',
    date: '2025-10-05',
    author: 'Anil Madhavapeddy',
    description: 'Report from the second PROPL workshop in Singapore, featuring Sadiq Jaffer\'s talk on TESSERA and building classifiers for solar farms in minutes on a laptop.',
    url: 'https://anil.recoil.org/notes/icfp25-propl',
    tags: ['community', 'research'],
  },
  {
    id: 'video-geoawesome',
    title: 'Video: Building a Global Open-Source Geospatial Foundation Model',
    date: '2025-11-30',
    author: 'Geoawesome',
    description: 'Interview covering TESSERA\'s open-source philosophy, the engineering of a global-scale geospatial foundation model, and plans for the future.',
    url: 'https://www.youtube.com/watch?v=u3_HxRJE8Ss',
    tags: ['video', 'community'],
  },
  {
    id: 'video-ecosystem-resilience',
    title: 'Video: Foundational AI to Forecast Ecosystem Resilience',
    date: '2025-11-24',
    author: 'Srinivasan Keshav, David A. Coomes',
    description: 'Workshop presentation at Pembroke College on applying foundational AI methods to predict ecosystem health and resilience.',
    url: 'https://watch.eeg.cl.cam.ac.uk/w/hanDLh2nzjXY4yL1akVEYh',
    tags: ['video', 'conservation'],
  },
  {
    id: 'geotessera-python-release',
    title: 'GeoTessera Python library released for geospatial embeddings',
    date: '2025-08-31',
    author: 'Anil Madhavapeddy',
    description: 'Announcing geotessera, a Python library and CLI for downloading and visualising TESSERA embeddings, with coverage tools and false-colour rendering.',
    url: 'https://anil.recoil.org/notes/geotessera-python',
    tags: ['engineering', 'python'],
  },
  {
    id: 'ars-technica-hedgehogs',
    title: 'Can AI detect hedgehogs from space? Maybe if you find brambles first',
    date: '2025-09-26',
    author: 'Benj Edwards',
    description: '',
    url: 'https://arstechnica.com/ai/2025/09/can-ai-detect-hedgehogs-from-space-maybe-if-you-find-brambles-first/',
    tags: ['conservation', 'community'],
    minor: true,
  },
  {
    id: 'brambles-from-space',
    title: 'Can a model trained on satellite data really find brambles on the ground?',
    date: '2025-09-24',
    author: 'Sadiq Jaffer',
    description: 'A field validation study testing whether a machine learning model using TESSERA embeddings can accurately predict bramble locations from satellite imagery.',
    url: 'https://toao.com/blog/can-we-really-see-brambles-from-space',
    tags: ['research', 'conservation'],
  },
  {
    id: 'silage-storage-tessera',
    title: 'Finding silage storage with TESSERA embeddings',
    date: '2025-09-05',
    author: 'Samuel Barrett',
    description: '',
    url: 'https://www.linkedin.com/posts/samuel-barrett-b86b85171_finding-silage-storage-with-tessera-embeddings-ugcPost-7369734079144955908-kdzM',
    tags: ['social', 'classification'],
    minor: true,
  },
  {
    id: 'tee-v3.0.0',
    title: 'TEE v3.0.0: Validation panel and client-side UMAP',
    date: '2026-03-09',
    author: 'Srinivasan Keshav',
    description: 'New validation panel with learning-curve evaluation and tunable hyperparameters. Moved UMAP computation to a client-side Web Worker, replaced GeoTIFF pyramids with PNG+JSON, added granular pipeline progress, and improved label management with a split-view panel.',
    url: 'https://github.com/ucam-eo/TEE/releases/tag/v3.0.0',
    tags: ['release', 'web'],
  },
  {
    id: 'terrabytes-tessera-blueprint',
    title: 'TESSERA: A Blueprint for Earth Observation Foundation Models',
    date: '2026-02-15',
    author: 'Rakshith Sathish',
    description: 'An independent review of TESSERA\'s architecture, training strategy, and open-source accessibility, with analysis of its strengths and areas for improvement.',
    url: 'https://terrabytes.substack.com/p/tessera-a-blueprint-for-earth-observation',
    tags: ['research', 'community'],
  },
  {
    id: 'tee-v2.0.0',
    title: 'TEE v2.0.0: Authentication, label export, and map export',
    date: '2026-02-20',
    author: 'Srinivasan Keshav',
    description: 'Major release adding per-user authentication with bcrypt, disk quotas, read-only demo mode, high-res map export as JPG, label export with 128-dim embeddings, satellite source selector, and Gunicorn/Apache production deployment.',
    url: 'https://github.com/ucam-eo/TEE/releases/tag/v2.0.0',
    tags: ['release', 'web'],
  },
  {
    id: 'conservation-foundation-models',
    title: 'Could geospatial foundation models help improve conservation effectiveness?',
    date: '2026-01-16',
    author: 'Julia P. G. Jones',
    description: 'How geospatial foundation models like TESSERA could transform conservation by integrating satellite data with ecological information to improve habitat mapping and policy decisions.',
    url: 'https://about.conservationevidence.com/2026/01/16/geospatial-foundation-models/',
    tags: ['conservation', 'community'],
  },
  {
    id: 'linkedin-uk-embeddings-2025',
    title: 'TESSERA open planetary embeddings for 2025 now published for the entire UK',
    date: '2026-01-03',
    author: 'Anil Madhavapeddy',
    description: '',
    url: 'https://www.linkedin.com/posts/anilmadhavapeddy_team-tessera-has-open-planetary-embeddings-activity-7413185711761170432-imfr',
    tags: ['social', 'community'],
    minor: true,
  },
  {
    id: 'earth-embeddings-taxonomy',
    title: 'Paper: Earth Embeddings as Products: Taxonomy, Ecosystem, and Standardized Access',
    date: '2026-01-19',
    author: 'Heng Fang et al.',
    description: '',
    url: 'https://arxiv.org/abs/2601.13134',
    tags: ['research', 'community'],
    minor: true,
  },
  {
    id: 'travelling-tessera-w4',
    title: 'Travelling and tracking TESSERA activity',
    date: '2026-01-25',
    author: 'Anil Madhavapeddy',
    description: 'Porting TESSERA to Zarr, a new preprint on standardising geoembedding access, SIDL podcast coverage, and TESSERA support merged into TorchGeo.',
    url: 'https://anil.recoil.org/notes/2026w4',
    tags: ['engineering', 'community'],
  },
  {
    id: 'video-new-earth-language',
    title: 'Video: TESSERA — A New Earth Language',
    date: '2026-01-28',
    author: 'GIS & Research Group',
    description: 'Overview of the TESSERA foundation model and its approach to encoding the Earth\'s surface as a new language for geospatial analysis.',
    url: 'https://www.youtube.com/watch?v=I4sBoCKMidA',
    tags: ['video', 'community'],
  },
  {
    id: 'video-ai-for-good',
    title: 'Video: Introduction to TESSERA at AI for Good',
    date: '2026-01-23',
    author: 'Zhengpeng Feng',
    description: 'Presentation at the AI for Good seminar introducing TESSERA\'s temporal embedding approach for satellite imagery analysis.',
    url: 'https://youtu.be/9yrpwFrwbGY?t=645',
    tags: ['video', 'community'],
  },
  {
    id: 'video-sidl-podcast',
    title: 'Podcast: TESSERA on Satellite Image Deep Learning',
    date: '2026-01-21',
    author: 'Sadiq Jaffer, Zhengpeng Feng',
    description: 'Podcast with Robin Cole covering temporal embeddings, self-supervised training at petabyte scale, wildfire detection, and plans for TESSERA v2.',
    url: 'https://www.satellite-image-deep-learning.com/p/tessera-a-temporal-foundation-model',
    tags: ['video', 'community'],
  },
  {
    id: 'tee-v1.4.0-stable',
    title: 'TEE v1.4.0: PCA as fast alternative to UMAP',
    date: '2026-02-04',
    author: 'Srinivasan Keshav',
    description: 'Added PCA as a fast alternative to UMAP for 3D embedding projection, enabling quicker dimensionality reduction for interactive exploration.',
    url: 'https://github.com/ucam-eo/TEE/releases/tag/v1.4.0-stable',
    tags: ['release', 'web'],
  },
  {
    id: 'geotessera-v0.7.5',
    title: 'geotessera v0.7.5: Faster startup and coordinate clamping',
    date: '2026-02-15',
    author: 'geotessera',
    description: 'Reduced startup time, auto-snap coordinates to valid tile centers, switched to pandas MultiIndex lookups, and split coverage data into per-year files for the globe viewer.',
    url: 'https://github.com/ucam-eo/geotessera/releases/tag/v0.7.5',
    tags: ['release', 'python'],
  },
  {
    id: 'geotessera-v0.7.4',
    title: 'geotessera v0.7.4: Single-tile queries and MIT license clarification',
    date: '2026-01-27',
    author: 'geotessera',
    description: 'New --tile option for single-tile download and coverage queries, enhanced --bbox supporting both formats, and resolved README/LICENSE mismatch.',
    url: 'https://github.com/ucam-eo/geotessera/releases/tag/v0.7.4',
    tags: ['release', 'python'],
  },
  {
    id: 'geotessera-v0.7.3',
    title: 'geotessera v0.7.3: Registry and embeddings scanning improvements',
    date: '2025-12-17',
    author: 'geotessera',
    description: 'Retired Pooch text manifests in favour of Parquet, added tolerance for incomplete embedding directories, and improved warning diagnostics.',
    url: 'https://github.com/ucam-eo/geotessera/releases/tag/v0.7.3',
    tags: ['release', 'python'],
  },
  {
    id: 'geotessera-v0.7.2',
    title: 'geotessera v0.7.2: Windows support and robust embeddings discovery',
    date: '2025-12-02',
    author: 'geotessera',
    description: 'Added Windows platform support with conda CI and PowerShell tests, fixed coordinate printing order, and resolved tile discovery false negatives.',
    url: 'https://github.com/ucam-eo/geotessera/releases/tag/v0.7.2',
    tags: ['release', 'python'],
  },
  {
    id: 'geotessera-python-0-7',
    title: 'GeoTessera 0.7 out with efficient sampling and Zarr support',
    date: '2025-11-17',
    author: 'Anil Madhavapeddy',
    description: 'GeoTessera 0.7 transitions to GeoParquet databases for faster initialization, adds Zarr format support for distributed storage, and introduces new sampling APIs for downstream tasks like solar panel detection.',
    url: 'https://anil.recoil.org/notes/geotessera-python-0-7',
    tags: ['engineering', 'python'],
  },
  {
    id: 'geotessera-v0.7.1',
    title: 'geotessera v0.7.1: Zarr format support',
    date: '2025-11-19',
    author: 'geotessera',
    description: 'New --format zarr option for cloud-native downloads with xarray integration, built-in compression, and georeferencing metadata. Added registry scan command.',
    url: 'https://github.com/ucam-eo/geotessera/releases/tag/v0.7.1',
    tags: ['release', 'python'],
  },
  {
    id: 'geotessera-v0.7.0',
    title: 'geotessera v0.7.0: GeoParquet registry and new APIs',
    date: '2025-11-11',
    author: 'geotessera',
    description: 'Major release transitioning to Parquet-based registry, adding point sampling and mosaic APIs, SHA256 verification, lazy iterators, 3D globe coverage viewer, and CRAM test suite.',
    url: 'https://github.com/ucam-eo/geotessera/releases/tag/v0.7.0',
    tags: ['release', 'python'],
  },
];
