export const siteConfig = {
  title: 'TESSERA',
  subtitle: 'A pixel-wise earth observation foundation model',
  social: {
    github: 'https://github.com/ucam-eo',
    bluesky: 'https://bsky.app/profile/geotessera.org',
    twitter: 'https://x.com/geotessera',
    linkedin: 'https://www.linkedin.com/company/ucam-eeg/',
    zulip: 'https://eeg.zulipchat.com',
  },
  tasks: [
    { name: 'Classification', tag: 'classification', description: 'Categorize land cover types from satellite embeddings' },
    { name: 'Segmentation', tag: 'segmentation', description: 'Detect and outline specific features in imagery' },
    { name: 'Change Detection', tag: 'change-detection', description: 'Monitor landscape changes over time' },
    { name: 'Canopy Height', tag: 'canopy-height', description: 'Estimate vegetation height from embeddings' },
    { name: 'Land Cover', tag: 'land-cover', description: 'Map land use and land cover at scale' },
    { name: 'Crop Mapping', tag: 'crop-mapping', description: 'Identify and classify agricultural crops' },
    { name: 'Solar Panels', tag: 'solar', description: 'Detect solar panel installations from space' },
  ] as const,
  roadmap: [
    {
      version: 'v1',
      status: 'available' as const,
      statusLabel: 'available',
      description: 'Global coverage, 2017–2025, npy format.',
      linkText: 'View coverage',
      linkUrl: '/coverage',
    },
    {
      version: 'v1.1',
      status: 'available' as const,
      statusLabel: 'available',
      description: 'Retrained model with more temporally stable embeddings, fewer low-observation artefacts, and wider coastal coverage.',
      linkText: 'Release notes',
      linkUrl: '/blog/2026-06-09-tessera-v1-1',
      link2Text: 'Weights',
      link2Url: 'https://huggingface.co/geotessera/TESSERA-V-1.1',
    },
    {
      version: 'v1.1-zarr',
      status: 'available' as const,
      statusLabel: 'available',
      description: 'Wall-to-wall v1.1 embeddings streamed over HTTPS via Zarr and Icechunk — no coverage requests needed.',
      linkText: 'Read the announcement',
      linkUrl: '/blog/2026-10-05-geotessera-0-11',
    },
    {
      version: 'v2',
      status: 'available' as const,
      statusLabel: 'beta available',
      description: 'Next-generation model with Matryoshka embeddings — variable-length representations for flexible compute/accuracy trade-offs. Beta embeddings are available on request.',
      linkText: 'Announcement',
      linkUrl: '/blog/2026-08-27-geotessera-a-year-on',
      link2Text: 'Isambard',
      link2Url: 'https://isambard.ac.uk/',
    },
    {
      version: 'v2-zarr',
      status: 'planned' as const,
      statusLabel: 'early 2027',
      description: 'Wall-to-wall v2 embeddings streamed via Zarr, with no coverage requests needed.',
    },
  ],
  docs: 'https://geotessera.readthedocs.io/',
  map: {
    catalogUrl: 'https://dl2.geotessera.org/zarr/v1/catalog.json',
    globalPreviewUrl: 'https://dl2.geotessera.org/zarr/v1/2025.zarr/global_rgb',
    initialCenter: [0.1218, 52.2053] as [number, number],
    initialZoom: 12,
    cambridgeCenter: [0.1218, 52.2053] as [number, number],
    cambridgeZoom: 12,
    ukCenter: [-2, 54] as [number, number],
    ukZoom: 5,
  },
} as const;

export type TaskConfig = (typeof siteConfig.tasks)[number];
