export const siteConfig = {
  title: 'TESSERA',
  subtitle: 'A pixel-wise earth observation foundation model',
  social: {
    github: 'https://github.com/ucam-eo',
    bluesky: 'https://bsky.app/profile/geotessera.org',
    twitter: 'https://x.com/geotessera',
    linkedin: 'https://www.linkedin.com/company/ucam-eeg/',
    zulip: 'https://eeg.zulipchat.com',
  },
  tasks: [
    { name: 'Classification', tag: 'classification', description: 'Categorize land cover types from satellite embeddings' },
    { name: 'Segmentation', tag: 'segmentation', description: 'Detect and outline specific features in imagery' },
    { name: 'Change Detection', tag: 'change-detection', description: 'Monitor landscape changes over time' },
    { name: 'Canopy Height', tag: 'canopy-height', description: 'Estimate vegetation height from embeddings' },
    { name: 'Land Cover', tag: 'land-cover', description: 'Map land use and land cover at scale' },
    { name: 'Crop Mapping', tag: 'crop-mapping', description: 'Identify and classify agricultural crops' },
    { name: 'Solar Panels', tag: 'solar', description: 'Detect solar panel installations from space' },
  ] as const,
  roadmap: [
    {
      version: 'v1',
      status: 'available' as const,
      statusLabel: 'available',
      description: 'Global coverage, 2017–2025, npy format.',
      linkText: 'View coverage',
      linkUrl: '/coverage',
      link2Text: 'Request embeddings',
      link2Url: 'https://github.com/ucam-eo/geotessera/issues',
    },
    {
      version: 'v1-zarr',
      status: 'ongoing' as const,
      statusLabel: 'in development',
      description: 'HTTP streaming via Zarr — currently transcoding tiles, which will take some time.',
      linkText: 'Zulip thread',
      linkUrl: 'https://eeg.zulipchat.com/#narrow/channel/527258-Tessera/topic/zarr.20file.20format/with/578418959',
    },
    {
      version: 'v1.1',
      status: 'available' as const,
      statusLabel: 'available',
      description: 'Retrained model with more temporally stable embeddings, fewer low-observation artefacts, and wider coastal coverage.',
      linkText: 'Release notes',
      linkUrl: '/blog/2026-06-02-tessera-v1-1',
      link2Text: 'Weights',
      link2Url: 'https://huggingface.co/geotessera/TESSERA-V-1.1',
    },
    {
      version: 'v2',
      status: 'planned' as const,
      statusLabel: 'late summer 2026',
      description: 'Next-generation model with Matryoshka embeddings — variable-length representations for flexible compute/accuracy trade-offs. Supported by',
      linkText: 'UKRI AI for Science',
      linkUrl: 'https://www.ukri.org/',
      link2Text: 'Isambard',
      link2Url: 'https://isambard.ac.uk/',
    },
  ],
  docs: 'https://geotessera.readthedocs.io/',
  map: {
    catalogUrl: 'https://dl2.geotessera.org/zarr/v1/catalog.json',
    globalPreviewUrl: 'https://dl2.geotessera.org/zarr/v1/2025.zarr/global_rgb',
    initialCenter: [0.1218, 52.2053] as [number, number],
    initialZoom: 12,
    cambridgeCenter: [0.1218, 52.2053] as [number, number],
    cambridgeZoom: 12,
    ukCenter: [-2, 54] as [number, number],
    ukZoom: 5,
  },
} as const;

export type TaskConfig = (typeof siteConfig.tasks)[number];
