<script lang="ts">
  import CropUmap from '@/components/CropUmap.svelte';
  import Footer from '@/components/Footer.svelte';

  function goFullscreen() {
    const el = document.querySelector('.umap-wrapper');
    if (el) (el as HTMLElement).requestFullscreen();
  }
</script>

<div class="crop-umap-page">
  <header class="page-header">
    <h1>CROME-TESSERA Crop UMAP</h1>
    <p class="subtitle">Interactive 3D embedding space of 210,000 crop cells from England</p>
  </header>

  <div class="description">
    <p>This visualisation projects TESSERA's 128-dimensional embeddings for over 210,000 hexagonal cells from England's <a href="https://www.data.gov.uk/dataset/be5d88c9-acfb-4052-bf6b-ee9a416cfe60/crop-map-of-england-crome-2024" target="_blank" rel="noopener">CROME 2024</a> crop map into three dimensions using UMAP. Each point is coloured by its crop class.</p>
    <p>Crops with similar seasonal growth patterns cluster together in the embedding space — winter cereals group tightly, as do permanent grasslands — demonstrating that TESSERA captures fine-grained phenological variation from the raw spectral-temporal signal without any labelled training data.</p>
    <ul class="instructions">
      <li><strong>Drag</strong> to rotate the 3D scatter plot</li>
      <li><strong>Scroll</strong> to zoom in and out</li>
      <li><strong>Click a point</strong> to inspect the crop cell and fly to its location on the satellite map</li>
      <li><strong>Click a crop</strong> in the legend to toggle its visibility</li>
      <li><strong>Hover a crop</strong> in the legend to highlight only that class</li>
    </ul>
    <button class="fullscreen-btn" onclick={goFullscreen}>
      <svg viewBox="0 0 20 20" fill="currentColor" width="18" height="18"><path d="M3 3h6v2H5v4H3V3zm8 0h6v6h-2V5h-4V3zM5 11H3v6h6v-2H5v-4zm10 0v4h-4v2h6v-6h-2z"/></svg>
      Go fullscreen
    </button>
  </div>

  <CropUmap />

  <div class="credits">
    <p>UMAP by <a href="https://toao.com" target="_blank" rel="noopener">Sadiq Jaffer</a>. Crop data from <a href="https://www.data.gov.uk/dataset/be5d88c9-acfb-4052-bf6b-ee9a416cfe60/crop-map-of-england-crome-2024" target="_blank" rel="noopener">CROME 2024</a> (Defra). Embeddings generated by <a href="/">TESSERA</a>.</p>
  </div>

  <Footer />
</div>

<style>
  .crop-umap-page {
    padding: 40px 32px 0;
  }

  .page-header {
    text-align: center;
    margin-bottom: 24px;
  }

  .page-header h1 {
    font-size: 28px;
    font-weight: 300;
    letter-spacing: 1px;
    color: var(--text-primary);
    margin-bottom: 6px;
  }

  .subtitle {
    font-size: 14px;
    color: var(--text-muted);
    letter-spacing: 0.5px;
  }

  .description {
    max-width: 680px;
    margin: 0 auto 24px;
    font-size: 14px;
    line-height: 1.7;
    color: var(--text-secondary);
  }

  .description p {
    margin-bottom: 12px;
  }

  .instructions {
    list-style: none;
    padding: 0;
    margin: 12px 0 20px;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 6px 24px;
    font-size: 13px;
    color: var(--text-muted);
  }

  .instructions strong {
    color: var(--text-secondary);
  }

  .fullscreen-btn {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 10px 20px;
    background: rgba(138, 180, 160, 0.12);
    border: 1px solid rgba(138, 180, 160, 0.3);
    border-radius: 6px;
    color: #8ab4a0;
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    transition: background 0.15s, border-color 0.15s;
  }

  .fullscreen-btn:hover {
    background: rgba(138, 180, 160, 0.2);
    border-color: rgba(138, 180, 160, 0.5);
  }

  .credits {
    max-width: 680px;
    margin: 20px auto 0;
    font-size: 12px;
    color: var(--text-muted);
    text-align: center;
  }

  .credits a {
    color: var(--accent-dim);
    text-decoration: none;
  }

  @media (max-width: 700px) {
    .crop-umap-page { padding: 24px 16px 0; }
    .page-header h1 { font-size: 22px; }
    .instructions { grid-template-columns: 1fr; }
  }
</style>
